version: '3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
