stages:
  - deploy

variables:
  SPLUNK_ALERT_PATH: "/opt/splunk/etc/apps/SplunkEnterpriseSecuritySuite/local/savedsearches.conf"
  SPLUNK_DASHBOARD_PATH: "/opt/splunk/etc/apps/search/local/data/ui/views/"
  #/opt/splunk/etc/apps/search/default/data/ui/views
  # Set PASSWORD as secret variable

deploy_alert:
  stage: deploy
  tags:
    - splunk
  script:
    - echo "Deploying alert configuration to Splunk server..."
    - echo $PASSWORD | sudo -S cp savedsearches.conf $SPLUNK_ALERT_PATH
    - echo "Deployment Rules complete."
    


deploy_dashboard:
  stage: deploy
  tags:
    - splunk
  script:
    - echo "Deploying dashboard configurations to Splunk server..."
    - for file in dashboard/*.xml; do
        echo $PASSWORD | sudo -S cp "$file" $SPLUNK_DASHBOARD_PATH;
      done
    - echo "Deployment Dashboards complete."

restart_splunk_server:
  stage: deploy
  tags:
    - splunk
  script:
    - echo "Restart Splunk..."
    - echo $PASSWORD | sudo -S /opt/splunk/bin/splunk restart
    - echo "Splunk Restart complete :\)"
