[tool.poetry]
name = "ansible-playbook-manager"
version = "0.1.0"
description = "A CLI tool to manage Ansible playbooks"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0"
ansible = "^5.0.0"

[tool.poetry.scripts]
manage-playbooks = "manage_playbooks:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

