---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - install_mimikatz
    - generate_payload
#    - winrm
#    - check_tools
#    - dump_lsass
#    - exfiltrate_lsass
#    - kerberoasting
#    - asrep_roasting
#    - dcsync_attack
#    - dcshadow_attack

