---
- name: Villain
  copy:
    dest: /opt/run_mimikatz.sh
    content: |
      #!/usr/bin/expect -f
      set timeout -1
      spawn villain -q
      expect "Villain > "
      send "backdoors"
      interact

- name: Make the script executable
  file:
    path: /opt/run_mimikatz.sh
    mode: '0755'


- name: Run the Villain
  shell: /opt/run_mimikatz.sh
