---
- name: Villain
  copy:
    dest: /opt/install_mimikatz.py
    content: |
      import pexpect
      import re
      import time
      villain_prompt = '\x1b[4mVillain\x1b[0m > '
      child = pexpect.spawn('villain -q', encoding='utf-8', timeout=50)
      time.sleep(1.5)
      child.expect(re.escape(villain_prompt))
      child.sendline('backdoors')
      child.expect(re.escape(villain_prompt))
      child.sendline('flee')
      agents_output = child.before
      print("Agents Output:\n", agents_output)

- name: Make the script executable
  file:
    path: /opt/install_mimikatz.py
    mode: '0755'


- name: Run the Villain
  shell: python3 /opt/install_mimikatz.py
  register: villain_output

- name: Display the output
  debug:
    msg: "{{ villain_output.stdout }}"
