---
- name: Villain
  copy:
    dest: /opt/install_mimikatz.py
    content: |
      import pexpect
      import re
      import json
      import time
      villain_prompt = '\x1b[4mVillain\x1b[0m > '
      child = pexpect.spawn('villain -q', encoding='utf-8', timeout=50)
      time.sleep(1.5)
      child.expect(re.escape(villain_prompt))
      child.sendline('backdoors')
      child.expect(re.escape(villain_prompt))
      child.sendline('flee')
      agents_output = child.before

      clean_data = re.sub(r'\u001b\[.*?m|\u0002', '', agents_output)
      
      pattern = r'(\S+)\s+(\S+)\s+(powershell\.exe)\s+(hoaxshell)\s+(\S+)\s+(\S+)'
      
      matches = re.findall(pattern, clean_data)
      
      session_info_list = []
      
      if matches:
          for match in matches:
              session_info = {
                  "Session ID": match[0],
                  "IP Address": match[1],
                  "Shell": match[2],
                  "Listener": match[3],
                  "Stability": match[4],
                  "Status": match[5]
              }
              session_info_list.append(session_info)
      
      json_data = json.dumps(session_info_list, indent=4)
      
      with open('session.json', 'w') as json_file:
          json_file.write(json_data)
      
      print(json_data)

- name: Make the script executable
  file:
    path: /opt/install_mimikatz.py
    mode: '0755'


- name: Run the Villain
  shell: python3 /opt/install_mimikatz.py
  register: villain_output

- name: Display the output
  debug:
    msg: "{{ villain_output.stdout }}"
