domain: "DC01.local"
target_ip_admin: "192.168.56.20"
admin: "Administrator"
ntlm_admin: "2b576acbe6bcfda7294d6bd18041b8fe"
target_ip: "192.168.56.10"
username: "alice"
ntlm: "2b576acbe6bcfda7294d6bd18041b8fe"
interface: "eth2"
mimikatz_url: "http://yourserver/mimikatz.exe"
mimikatz_dest: "C:\\Windows\\Temp\\mimikatz.exe"
lsass_dump_dest: "C:\\Windows\\Temp\\lsass.dmp"
ngrok_authtoken: ""
ngrok_port: "8080"
